fix(microsoft): 401s only sometimes correctly classified (#1413)
regression coverage: without the fix in MicrosoftApiResponse.java this new
test's state captures `isTokenRefreshRequired()` erroneously returning true:

```
MicrosoftApiResponseTest > testDestinationFull PASSED

MicrosoftApiResponseTest > testUnrecognized401 FAILED
    java.lang.AssertionError: The subject was expected to be false, but was true
        at org.datatransferproject.transfer.microsoft.MicrosoftApiResponseTest.testUnrecognized401(MicrosoftApiResponseTest.java:130)

MicrosoftApiResponseTest > testBytesOnClosedResponse PASSED

MicrosoftApiResponseTest > testOkay PASSED

MicrosoftApiResponseTest > testInvalidTokenDetection PASSED

MicrosoftApiResponseTest > testErrorPermission PASSED

MicrosoftApiResponseTest > testErrorUnknown PASSED

MicrosoftMediaImporterTest > testImportItemAllSuccess PASSED

MicrosoftMediaImporterTest > testImportItemPermissionDenied PASSED

MicrosoftMediaImporterTest > testImportInsufficientStorage PASSED

MicrosoftMediaImporterTest > testCleanAlbumNames PASSED

MicrosoftMediaImporterTest > testImportUnrecognizedError PASSED
```