noop refactor as a pre-step to landing a new importer that needs some of this video logic (#1229)
* Move logic for importing photos into its own function

* remove jobId from getPhotoDescription since its not used

* make `getPhotoDescription` more generic

* Split out the logic for retrieving an input stream from a url to a reuseable function

* Rename PhotoResult to MediaResult, pull out the code that processes the mediaItemresult into a function

* Create GoogleMediaImporter as a copy of the GooglePhotosImporter but w/ copies for the video functions

* rename `uploadPhotoContent` to `uploadMediaContent`

* WIP: refork Photos importer + factor out Video logic

re-forking Photos code (as that's how this branch was originally
developed) because a lot of upstream changes have landed in video code
since then.

while I'm at it I'm also doing what I did with
MicrosoftMedia{Importer,Exporter} and trying to make the MediaImporter
not repeat itself, but at least factor our the common logic looping over
video vs. looping over photos objects internally.

this refactoring isn't perfect, but it's a baby step: in the future we
can use the abstractions added internally to this class to let _all_ the
adapters in the google package reuse this same code (both the Photos and
the Videos adapters).

state of this commit: doesn't compile quite yet:

  ```
  $ gradle test
  > Task :extensions:data-transfer:portability-data-transfer-google:compileJava FAILED
  /usr/local/google/home/zacsh/pub/src/dtp/extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/media/GoogleMediaImporter.java:188: error: incompatible types: invalid method reference
          this::importPhotoBatch);
          ^
      incompatible types: List<T> cannot be converted to List<PhotoModel>
    where T is a type-variable:
      T extends Object declared in method <T>importToAlbum(UUID,TokensAndUrlAuthData,List<T>,IdempotentImportExecutor,String)
  Note: /usr/local/google/home/zacsh/pub/src/dtp/extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosInterface.java uses or overrides a deprecated API.
  Note: Recompile with -Xlint:deprecation for details.
  Note: Some input files use unchecked or unsafe operations.
  Note: Recompile with -Xlint:unchecked for details.
  Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
  1 error

  FAILURE: Build failed with an exception.
  ```

* WIP: fixed generics error in GoogleMediaImporter

had one too many generic declarations (shouldn't have had `<T>` on the
interface's method declaration itself, but rather strictly on the
_interface_)

note: this commit is also not compiling, but for difference reasons now.

* WIP: fix revert of PhotoResult move back to media package

* WIP: unit tests now compiling, but not done

not done as we've not yet updated the test for new functionality

* WIP: micro-step in factoring out batch video upload

this is a microstep because it's simply making the existing logic
static, right were it is, before we move it out (in a later commit).

* WIP: noop(refactor) fully moves video logic to interface

* completes fork of G...PhotosImporter into *Media*

TBD fast-follows for myself and gphotos folks:
1. more unit test coverage; how are we going to do that constructively?
   we want to probably move a lot of existing test logic into
   GoogleVideoInterface instead, and mock those APIs in our tests here.
2. more manual testing
3. long-term cleanups of gphotos things (eg: see all TODOs landed in
   this work)
4. long-term reconiling of gphotos upstream SDK interactions; eg:
  - sometimes we use raw HTTP - as with GooglePhotos* adapters
  - sometimes we use raw PhotosLibraryClient, as with GoogleVideos*
    adapters
  - reconciling these two will mean _one_ approach to gphotos SDKs can
    be taken and maintained, and further simplification of logic sharing
    across the adapters will naturally follow.

* noop(docs) embed previous commit message's TODOs

* noop(docs) one more place to point out where we are trying to de-dupe efforts

* noop(docs) make TODO more specific

* prefactor[squash me]: simplify by reverting new importer

* prefactor[squash me]: simplify by reverting `gradle test` tweak

---------

Co-authored-by: Siham Hussein <sihamh@google.com>